return {
  "williamboman/mason-lspconfig.nvim",
  opts = {
    ensure_installed = {
      "angularls",
      "ansiblels",
      "asm_lsp",
      "astro",
      "bashls",
      "clangd",
      "cmake",
      -- css
      "cssls",
      "tailwindcss",
      "unocss",
      -- docker
      "docker_compose_language_service",
      "dockerls",
      "emmet_language_server",
      "gopls",
      "gradle_ls",
      "graphql",
      "groovyls",
      "html",
      "jdtls",
      "eslint",
      "jsonls",
      "ast_grep",
      "kotlin_lsp",
      "ltex",
      "lua_ls",
      "marksman",
      "denols",
      "nginx_language_server",
      "powershell_es",
      "prismals",
      "buf_ls",
      "pyright",
      "ruff",
      "rust_analyzer",
      "sqlls",
      "svelte",
      "harper_ls",
      "tinymist",
      "vimls",
      "vue_ls",
      "lemminx",
      "gitlab_ci_ls",
      "yamlls",
      "zls"
    }
  }
}
